name: Run tests

on:
  push:
    branches: [ main, '[0-9]*.[0-9]*.x' ]
  pull_request:
    branches: [ main, '[0-9]*.[0-9]*.x' ]
  workflow_dispatch:

env:
  JDK_VERSION: 17

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}
      - name: Execute check without tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: check -x test
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JDK_VERSION }}

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test

      - name: Execute tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test
        env:
          CI: Github Action

      - name: Publish test report
        uses: mikepenz/action-junit-report@v4.3.1
        if: always() # always run even if the previous step fails
        with:
          check_name: JUnit Test Report
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true

      - name: Test Summary
        uses: actions/upload-artifact@v4.3.3  # upload test results
        if: always()
        with:
          name: test-results
          path: '**/build/test-results/test/TEST-*.xml'
