name: Publish artifacts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Specify the tag, branch, or commit to target for the publish action"
        required: true
        default: 'default'
        type: string

jobs:
  eventeria-messaging-contract:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-contract'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging-contract-cloudevents:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-contract-cloudevents'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging-json-jackson:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-json-jackson'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging-kafka:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-kafka'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging-spring:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-spring'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging-spring-integration:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-spring-integration'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging-spring-cloud-stream:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-spring-cloud-stream'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-domain:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-domain'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-domain-spring:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-domain-spring'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-validator:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-validator'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-timer-contract:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-timer-contract'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-timer:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-timer'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-timer-spring-integration:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-timer-spring-integration'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-messaging-timer-spring-redis:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-messaging-timer-spring-redis'
      target-ref: ${{ github.event.inputs.tag }}

  spring-boot-eventeria:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'spring-boot-eventeria'
      target-ref: ${{ github.event.inputs.tag }}

  eventeria-fake-spring-cloud-stream-binder-kafka:
    uses: ./.github/workflows/publish-module.yml
    secrets: inherit
    with:
      target-module: 'eventeria-fake-spring-cloud-stream-binder-kafka'
      target-ref: ${{ github.event.inputs.tag }}
